//;-*- mode: java -*-
/*
                        QueryJ

    Copyright (C) 2002-2007  Jose San Leandro Armendariz
                        chous@acm-sl.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Thanks to ACM S.L. for distributing this library under the GPL license.
    Contact info: chous@acm-sl.org
    Postal Address: c/Playa de Lagoa, 1
                    Urb. Valdecabanas
                    Boadilla del monte
                    28660 Madrid
                    Spain

 ******************************************************************************
 *
 * Filename: StatementFlagsElement.java
 *
 * Author: Jose San Leandro Armendariz
 *
 * Description: Models statement flags in custom-sql models.
 *
 */
package org.acmsl.queryj.tools.customsql;

/*
 * Importing project-specific classes.
 */
import org.acmsl.queryj.tools.customsql.IdentifiableElement;

/*
 * Importing JDK classes.
 */
import java.util.ArrayList;
import java.util.Collection;

/**
 * Models &statement flags in <i>custom-sql</i> models.
 * @author <a href="mailto:chous@acm-sl.org"
 *         >Jose San Leandro</a>
 */
public interface StatementFlags
    extends  IdentifiableElement
{
    /**
     * The <b>NO_GENERATED_KEYS</b> value for
     * <i>autogeneratekeys</i> attribute.
     */
    public static final String NO_GENERATED_KEYS = "NO_GENERATED_KEYS";

    /**
     * The <b>RETURN_GENERATED_KEYS</b> value for
     * <i>autogeneratekeys</i> attribute.
     */
    public static final String RETURN_GENERATED_KEYS = "RETURN_GENERATED_KEYS";

    /**
     * The <b>FETCH_FORWARD</b> value for <i>fetchdirection</i> attribute.
     */
    public static final String FETCH_FORWARD = "FETCH_FORWARD";

    /**
     * The <b>FETCH_REVERSE</b> value for <i>fetchdirection</i> attribute.
     */
    public static final String FETCH_REVERSE = "FETCH_REVERSE";

    /**
     * The <b>FETCH_UNKNOWN</b> value for <i>fetchdirection</i> attribute.
     */
    public static final String FETCH_UNKNOWN = "FETCH_UNKNOWN";

    /**
     * The <b>CLOSE_CURRENT_RESULT</b> value for <i>moreresults</i> attribute.
     */
    public static final String CLOSE_CURRENT_RESULT = "CLOSE_CURRENT_RESULT";

    /**
     * The <b>KEEP_CURRENT_RESULT</b> value for <i>moreresults</i> attribute.
     */
    public static final String KEEP_CURRENT_RESULT = "KEEP_CURRENT_RESULT";

    /**
     * The <b>CLOSE_ALL_RESULTS</b> value for <i>moreresults</i> attribute.
     */
    public static final String CLOSE_ALL_RESULTS = "CLOSE_ALL_RESULTS";

    /**
     * Retrieves the <i>autogeneratedkeys</i> attribute.
     * @return such value.
     */
    public String getAutogeneratedKeys();

    /**
     * Retrieves the <i>fetchsize</i> attribute.
     * @return such value.
     */
    public Integer getFetchSize();

    /**
     * Retrieves the <i>maxfieldsize</i> attribute.
     * @return such value.
     */
    public Integer getMaxFieldSize();
    
    /**
     * Retrieves the <i>maxrows</i> attribute.
     * @return such value.
     */
    public Integer getMaxRows();

    /**
     * Retrieves the <i>querytimeout</i> attribute.
     * @return such value.
     */
    public Integer getQueryTimeout();

    /**
     * Retrieves the <i>fetchdirection</i> attribute.
     * @return such value.
     */
    public String getFetchDirection();

    /**
     * Retrieves the <i>escapeprocessing</i> attribute.
     * @return such value.
     */
    public Boolean getEscapeProcessing();

    /**
     * Retrieves the <i>moreresults</i> attribute.
     * @return such value.
     */
    public String getMoreResults();

    /**
     * Retrieves the cursor name.
     * @return such information.
     */
    public String getCursorName();
}
