/*
                        QueryJ

    Copyright (C) 2002  Jose San Leandro Armendariz
                        jsanleandro@yahoo.es
                        chousz@yahoo.com

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Thanks to ACM S.L. for distributing this library under the GPL license.
    Contact info: jsanleandro@yahoo.es
    Postal Address: c/Playa de Lagoa, 1
                    Urb. Valdecabanas
                    Boadilla del monte
                    28660 Madrid
                    Spain

 ******************************************************************************
 *
 * Filename: $RCSfile$
 *
 * Author: Jose San Leandro Armendariz
 *
 * Description: Is able to create sql.xml <statement-flags> element instances
 *              from their attributes, while being parsed by Digester.
 *
 */
package org.acmsl.queryj.tools.customsql.xml;

/*
 * Importing some project classes.
 */
import org.acmsl.queryj.tools.customsql.StatementFlagsElement;
import org.acmsl.queryj.tools.customsql.xml.ElementFactory;

/*
 * Importing some ACM-SL classes.
 */
import org.acmsl.commons.utils.ConversionUtils;

/*
 * Importing some additional classes.
 */
import org.apache.commons.digester.Digester;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 * Is able to create sql.xml &lt;statement-flags&gt; element instances
 * from their attributes, while being parsed by Digester.
 * @author <a href="mailto:jsanleandro@yahoo.es"
 *         >Jose San Leandro</a>
 */
public class StatementFlagsElementFactory
    extends  ElementFactory
{
    /**
     * Creates a StatementFlagsElementFactory instance.
     */
    public StatementFlagsElementFactory() {};

    /**
     * Creates a StatementFlagsElement instance from given SAX
     * attributes.
     * @param attributes the attributes.
     * @param digester the Digester instance.
     * @param conversionUtils the ConversionUtils instance.
     * @return the &lt;sql&gt; information.
     * @throws SAXException if the attributes are not valid.
     * @precondition attributes != null
     * @precondition digester != null
     * @precondition conversionUtils != null
     */
    public Object createObject(
        final Attributes attributes,
        final Digester digester,
        final ConversionUtils conversionUtils)
      throws SAXException
    {
        StatementFlagsElement result = null;

        String t_strId = attributes.getValue("id");

        String t_strAutogeneratedKeys =
            attributes.getValue("autogeneratedkeys");

        Integer t_iFetchSize = null;

        String t_strFetchSize = 
            attributes.getValue("fetchsize");

        if  (t_strFetchSize != null)
        {
            t_iFetchSize =
                new Integer(conversionUtils.toInt(t_strFetchSize));
        }

        Integer t_iMaxFieldSize = null;

        String t_strMaxFieldSize = 
            attributes.getValue("maxfieldsize");

        if  (t_strMaxFieldSize != null)
        {
            t_iMaxFieldSize =
                new Integer(conversionUtils.toInt(t_strMaxFieldSize));
        }

        Integer t_iMaxRows = null;

        String t_strMaxRows = 
            attributes.getValue("maxrows");

        if  (t_strMaxRows != null)
        {
            t_iMaxRows =
                new Integer(conversionUtils.toInt(t_strMaxRows));
        }

        Integer t_iQueryTimeout = null;

        String t_strQueryTimeout = 
            attributes.getValue("querytimeout");

        if  (t_strQueryTimeout != null)
        {
            t_iQueryTimeout =
                new Integer(conversionUtils.toInt(t_strQueryTimeout));
        }

        String t_strFetchDirection = 
            attributes.getValue("fetchdirection");

        Boolean t_bEscapeProcessing = null;

        String t_strEscapeProcessing = 
            attributes.getValue("escapeprocessing");

        if  (t_strEscapeProcessing != null)
        {
            t_bEscapeProcessing =
                conversionUtils.toBoolean(t_strEscapeProcessing)
                ?  Boolean.TRUE
                :  Boolean.FALSE;
        }

        String t_strMoreResults = 
            attributes.getValue("moreresults");

        String t_strCursorName = 
            attributes.getValue("cursorname");

        result =
            new StatementFlagsElement(
                t_strId,
                t_strAutogeneratedKeys,
                t_iFetchSize,
                t_iMaxFieldSize,
                t_iMaxRows,
                t_iQueryTimeout,
                t_strFetchDirection,
                t_bEscapeProcessing,
                t_strMoreResults,
                t_strCursorName);

        return result;
    }
}
