/*
                      Project tests

Copyright (C) 2003  Jose San Leandro Armend?riz
chous@acm-sl.org

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Thanks to ACM S.L. for distributing this library under the GPL license.
Contact info: pepe@acm-sl.com
Postal Address: c/Playa de Lagoa, 1
Urb. Valdecaba?as
Boadilla del monte
28660 Madrid
Spain

******************************************************************************
*
* Filename: $RCSfile$
*
* Author: Jose San Leandro Armend?riz
*
* Description: Executes all tests defined for package
*              unittests.org.acmsl.queryj.tools.customsql.
*
*/
package unittests.org.acmsl.queryj.tools.customsql;

/*
* Importing project classes.
*/
// JUnitDoclet begin import
import org.acmsl.queryj.tools.customsql.StatementFlagsElement;
// JUnitDoclet end import

/*
* Importing JUnit classes.
*/
import junit.framework.TestCase;

/*
This file is part of  JUnitDoclet, a project to generate basic
test cases  from source code and  helping to keep them in sync
during refactoring.

Copyright (C) 2002-2005  ObjectFab GmbH  (http://www.objectfab.de/)

This library is  free software; you can redistribute it and/or
modify  it under the  terms of  the  GNU Lesser General Public
License as published  by the  Free Software Foundation; either
version 2.1  of the  License, or  (at your option)  any  later
version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You  should  have  received a  copy of the  GNU Lesser General
Public License along with this  library; if not, write  to the
Free  Software  Foundation, Inc.,  59 Temple Place,  Suite 330,
Boston, MA  02111-1307  USA
*/


/**
* Tests StatementFlagsElementTest class.
* @see org.acmsl.queryj.tools.customsql.StatementFlagsElement
*/
public class StatementFlagsElementTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  org.acmsl.queryj.tools.customsql.StatementFlagsElement statementflagselement = null;
  // JUnitDoclet end class
  
  /**
  * Creates a StatementFlagsElementTest with given name.
  * @param name such name.
  */
  public StatementFlagsElementTest(String name)
  {
    // JUnitDoclet begin method StatementFlagsElementTest
    super(name);
    // JUnitDoclet end method StatementFlagsElementTest
  }
  
  /**
  * Creates an instance of the tested class.
  * @return such instance.
  
  */
  public org.acmsl.queryj.tools.customsql.StatementFlagsElement createInstance()
  throws Exception
  {
    // JUnitDoclet begin method testcase.createInstance
    return
        new org.acmsl.queryj.tools.customsql.StatementFlagsElement(
            "statement-flags-1",
            org.acmsl.queryj.tools.customsql.StatementFlagsElement.NO_GENERATED_KEYS,
            new Integer(10),
            new Integer(100),
            new Integer(40),
            new Integer(30),
            org.acmsl.queryj.tools.customsql.StatementFlagsElement.FETCH_FORWARD,
            Boolean.TRUE,
            org.acmsl.queryj.tools.customsql.StatementFlagsElement.CLOSE_CURRENT_RESULT,
            "test");

    // JUnitDoclet end method testcase.createInstance
  }
  
  /**
  * Performs any required steps before each test.
  * @throws Exception if an unexpected situation occurs.
  */
  protected void setUp()
  throws Exception
  {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    statementflagselement = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  /**
  * Performs any required steps after each test.
  * @throws Exception if an unexpected situation occurs.
  */
  protected void tearDown()
  throws Exception
  {
    // JUnitDoclet begin method testcase.tearDown
    statementflagselement = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  /**
  * Tests StatementFlagsElementTestgetAutogeneratedKeys()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getAutogeneratedKeys()
  */
  public void testGetAutogeneratedKeys()
  throws Exception
  {
    // JUnitDoclet begin method getAutogeneratedKeys
    // JUnitDoclet end method getAutogeneratedKeys
  }
  
  /**
  * Tests StatementFlagsElementTestgetFetchSize()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getFetchSize()
  */
  public void testGetFetchSize()
  throws Exception
  {
    // JUnitDoclet begin method getFetchSize
    // JUnitDoclet end method getFetchSize
  }
  
  /**
  * Tests StatementFlagsElementTestgetMaxFieldSize()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getMaxFieldSize()
  */
  public void testGetMaxFieldSize()
  throws Exception
  {
    // JUnitDoclet begin method getMaxFieldSize
    // JUnitDoclet end method getMaxFieldSize
  }
  
  /**
  * Tests StatementFlagsElementTestgetMaxRows()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getMaxRows()
  */
  public void testGetMaxRows()
  throws Exception
  {
    // JUnitDoclet begin method getMaxRows
    // JUnitDoclet end method getMaxRows
  }
  
  /**
  * Tests StatementFlagsElementTestgetQueryTimeout()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getQueryTimeout()
  */
  public void testGetQueryTimeout()
  throws Exception
  {
    // JUnitDoclet begin method getQueryTimeout
    // JUnitDoclet end method getQueryTimeout
  }
  
  /**
  * Tests StatementFlagsElementTestgetFetchDirection()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getFetchDirection()
  */
  public void testGetFetchDirection()
  throws Exception
  {
    // JUnitDoclet begin method getFetchDirection
    // JUnitDoclet end method getFetchDirection
  }
  
  /**
  * Tests StatementFlagsElementTestgetEscapeProcessing()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getEscapeProcessing()
  */
  public void testGetEscapeProcessing()
  throws Exception
  {
    // JUnitDoclet begin method getEscapeProcessing
    // JUnitDoclet end method getEscapeProcessing
  }
  
  /**
  * Tests StatementFlagsElementTestgetMoreResults()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getMoreResults()
  */
  public void testGetMoreResults()
  throws Exception
  {
    // JUnitDoclet begin method getMoreResults
    // JUnitDoclet end method getMoreResults
  }
  
  /**
  * Tests StatementFlagsElementTestgetCursorName()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#getCursorName()
  */
  public void testGetCursorName()
  throws Exception
  {
    // JUnitDoclet begin method getCursorName
    // JUnitDoclet end method getCursorName
  }
  
  /**
  * Tests StatementFlagsElementTesttoString()
  * @throws Exception if an unexpected situation occurs.
  * @see org.acmsl.queryj.tools.customsql.StatementFlagsElement#toString()
  */
  public void testToString()
  throws Exception
  {
    // JUnitDoclet begin method toString
    // JUnitDoclet end method toString
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  * @throws Exception if an unexpected situation occurs.
  */
  public void testVault()
  throws Exception
  {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args)
  {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(StatementFlagsElementTest.class);
    // JUnitDoclet end method testcase.main
  }
}
