/*
                        QueryJ

    Copyright (C) 2002-today  Jose San Leandro Armendariz
                              chous@acm-sl.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Thanks to ACM S.L. for distributing this library under the GPL license.
    Contact info: jose.sanleandro@acm-sl.com

 *****************************************************************************
 *
 * Filename: BasePerForeignKeyTemplate.java
 *
 * Author: Jose San Leandro Armendariz
 *
 * Description: Base logic for all per-FK templates.
 *
 */
package org.acmsl.queryj.tools.templates;

/*
 * Importing some project-specific classes.
 */
import org.acmsl.queryj.tools.metadata.DecoratorFactory;
import org.acmsl.queryj.tools.metadata.DecorationUtils;
import org.acmsl.queryj.tools.metadata.ForeignKeyDecorator;
import org.acmsl.queryj.tools.metadata.MetadataManager;
import org.acmsl.queryj.tools.metadata.MetadataTypeManager;
import org.acmsl.queryj.tools.metadata.vo.Attribute;
import org.acmsl.queryj.tools.metadata.vo.ForeignKey;
import org.acmsl.queryj.tools.PackageUtils;

/*
 * Importing some ACM-SL classes.
 */
import org.acmsl.commons.utils.EnglishGrammarUtils;
import org.acmsl.commons.utils.StringUtils;
import org.acmsl.commons.utils.StringValidator;

/*
 * Importing StringTemplate classes.
 */
import org.antlr.stringtemplate.StringTemplate;
import org.antlr.stringtemplate.StringTemplateGroup;

/*
 * Importing some JDK classes.
 */
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * Importing some JetBrains annotations.
 */
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Base logic for all per-fk templates.
 * @author <a href="mailto:chous@acm-sl.org">Jose San Leandro Armendariz</a>
 */
public abstract class BasePerForeignKeyTemplate<C extends BasePerForeignKeyTemplateContext>
    extends  AbstractBasePerForeignKeyTemplate<C>
{
    /**
     * Builds a <code>BasePerForeignKeyTemplate</code> using given
     * information.
     * @param context the {@link BasePerForeignKeyTemplateContext} instance.
     */
    public BasePerForeignKeyTemplate(@NotNull final C context)
    {
        super(context);
    }

    /**
     * Retrieves the source code generated by this template.
     * @param header the header.
     * @param context the {@link BasePerForeignKeyTemplateContext} instance.
     * @return such code.
     */
    @Override
    @NotNull
    protected String generateOutput(@NotNull final String header, @NotNull final C context)
    {
        return generateOutput(header, context, context.getMetadataManager());
    }

    /**
     * Retrieves the source code generated by this template.
     * @param header the header.
     * @param context the {@link BasePerForeignKeyTemplateContext} instance.
     * @param metadataManager the metadata manager.
     * @return such code.
     */
    @NotNull
    protected String generateOutput(
        @NotNull final String header, @NotNull final C context, @NotNull final MetadataManager metadataManager)
    {
        return
            generateOutput(
                context.getForeignKey(),
                metadataManager,
                context.getPackageName(),
                metadataManager.getEngineName(),
                metadataManager.getEngineVersion(),
                metadataManager.getQuote(),
                context.getBasePackageName(),
                context.getRepositoryName(),
                metadataManager.getMetadataTypeManager(),
                header,
                context.getDecoratorFactory(),
                StringUtils.getInstance(),
                DefaultThemeUtils.getInstance(),
                PackageUtils.getInstance(),
                StringValidator.getInstance(),
                EnglishGrammarUtils.getInstance(),
                MetaLanguageUtils.getInstance());
    }

    /**
     * Retrieves the source code generated by this template.
     * @param foreignKey the foreign key.
     * @param metadataManager the database metadata manager.
     * @param packageName the package name.
     * @param engineName the engine name.
     * @param engineVersion the engine version.
     * @param quote the identifier quote string.
     * @param basePackageName the base package name.
     * @param repositoryName the repository name.
     * @param metadataTypeManager the metadata type manager.
     * @param header the header.
     * @param decoratorFactory the <code>DecoratorFactory</code> instance.
     * @param stringUtils the StringUtils instance.
     * @param defaultThemeUtils the <code>DefaultThemeUtils</code> instance.
     * @param packageUtils the PackageUtils instance.
     * @param stringValidator the StringValidator instance.
     * @param englishGrammarUtils the EnglishGrammarUtils instance.
     * @param metaLanguageUtils the <code>MetaLanguageUtils</code> instance.
     * @return such code.
     */
    @SuppressWarnings("unused")
    protected String generateOutput(
        @NotNull final ForeignKey foreignKey,
        @NotNull final MetadataManager metadataManager,
        @NotNull final String packageName,
        @NotNull final String engineName,
        @NotNull final String engineVersion,
        @NotNull final String quote,
        @NotNull final String basePackageName,
        @NotNull final String repositoryName,
        @NotNull final MetadataTypeManager metadataTypeManager,
        @NotNull final String header,
        @NotNull final DecoratorFactory decoratorFactory,
        @NotNull final StringUtils stringUtils,
        @NotNull final DefaultThemeUtils defaultThemeUtils,
        @NotNull final PackageUtils packageUtils,
        @NotNull final StringValidator stringValidator,
        @NotNull final EnglishGrammarUtils englishGrammarUtils,
        @NotNull final MetaLanguageUtils metaLanguageUtils)
    {
        String result;

        @Nullable StringTemplateGroup t_Group = retrieveGroup();

        @Nullable StringTemplate t_Template = retrieveTemplate(t_Group);

        String t_strRepositoryName =
            stringUtils.capitalize(repositoryName, '_');

        fillParameters(
            new HashMap(),
            t_Template,
            new Integer[]
            {
                STARTING_YEAR,
                retrieveCurrentYear()
            },
            new ForeignKeyDecorator(foreignKey, metadataManager, decoratorFactory),
            engineName,
            engineVersion,
            basePackageName,
            packageUtils.retrieveDAOSubpackage(engineName),
            createTimestamp(),
            t_strRepositoryName,
            header,
            decoratorFactory,
            stringUtils);

        try
        {
            result = t_Template.toString();
        }
        catch (@NotNull final IllegalArgumentException invalidTemplate)
        {
            throw
                new InvalidTemplateException(
                    "invalid.per.foreign-key.template",
                    new Object[]
                    {
                        t_Template.getName(),
                        getTemplateName(),
                        foreignKey.getSourceTableName(),
                        foreignKey.getTargetTableName()
                    },
                    invalidTemplate);
        }

        return result;
    }

    /**
     * Fills the template parameters.
     * @param input the parameter container.
     * @param template the template.
     * @param copyrightYears the copyright years.
     * @param foreignKey the foreign key.
     * @param engineName the engine name.
     * @param engineVersion the engine version.
     * @param basePackageName the base package name.
     * @param subpackageName the subpackage.
     * @param timestamp the timestamp.
     * @param tableRepositoryName the table repository.
     * @param header the header.
     * @param decoratorFactory the <code>DecoratorFactory</code> instance.
     * @param stringUtils the <code>StringUtils</code> instance.
     */
    @SuppressWarnings("unused")
    protected void fillParameters(
        @NotNull final Map input,
        @NotNull final StringTemplate template,
        @NotNull final Integer[] copyrightYears,
        @NotNull final ForeignKey foreignKey,
        @NotNull final String engineName,
        @NotNull final String engineVersion,
        @NotNull final String basePackageName,
        @NotNull final String subpackageName,
        @NotNull final String timestamp,
        @NotNull final String tableRepositoryName,
        @NotNull final String header,
        @NotNull final DecoratorFactory decoratorFactory,
        @NotNull final StringUtils stringUtils)
    {
        template.setAttribute("input", input);

        fillCommonParameters(input, foreignKey, engineName, engineVersion);

        fillJavaHeaderParameters(input, header, copyrightYears, timestamp);

        fillPackageDeclarationParameters(
            input,
            basePackageName,
            subpackageName,
            foreignKey.getSourceTableName());

        fillProjectImportsParameters(
            input,
            basePackageName,
            subpackageName,
            foreignKey.getAttributes());

        fillClassParameters(
            input,
            foreignKey,
            engineName,
            engineVersion,
            timestamp,
            tableRepositoryName);
    }

    /**
     * Fills the common parameters.
     * @param input the input.
     * @param foreignKey the foreign key.
     * @param engineName the engine name.
     * @param engineVersion the engine version.
     */
    @SuppressWarnings("unchecked")
    protected void fillCommonParameters(
        @NotNull final Map input,
        @NotNull final ForeignKey foreignKey,
        @NotNull final String engineName,
        @NotNull final String engineVersion)
    {
        input.put("table_name",  foreignKey.getSourceTableName());
        input.put("foreign_key", foreignKey);
        input.put("engine_name", engineName);
        input.put("engine_version", engineVersion);
    }

    /**
     * Fills the parameters for <code>java_header</code> rule.
     * @param input the input.
     * @param header the header.
     * @param copyrightYears the copyright years.
     * @param timestamp the timestamp.
     */
    @SuppressWarnings("unchecked")
    protected void fillJavaHeaderParameters(
        @NotNull final Map input,
        @Nullable final String header,
        @NotNull final Integer[] copyrightYears,
        @NotNull final String timestamp)
    {
        input.put("copyright_years", copyrightYears);
        input.put("timestamp", timestamp);
        if  (   (header != null)
             && (!input.containsKey("header")))
        {
            input.put("header", processHeader(input, header));
        }
    }

    /**
     * Fills the parameters for <code>package_declaration</code> rule.
     * @param input the input.
     * @param basePackageName the base package name.
     * @param subpackageName the subpackage.
     * @param tableName the table name.
     */
    @SuppressWarnings("unchecked")
    protected void fillPackageDeclarationParameters(
        @NotNull final Map input,
        @NotNull final String basePackageName,
        @NotNull final String subpackageName,
        @NotNull final String tableName)
    {
        input.put("base_package_name", basePackageName);
        input.put("subpackage_name", subpackageName);
        input.put(
            "table_name_normalized_lowercased",
            normalizeLowercase(tableName, DecorationUtils.getInstance()));
    }

    /**
     * Fills the parameters for the <code>project_imports</code> rule.
     * @param input the input.
     * @param basePackageName the base package.
     * @param subpackageName the name of the subpackage.
     * @param fkAttributes the foreign-key attributes.
     */
    @SuppressWarnings("unchecked")
    protected void fillProjectImportsParameters(
        @NotNull final Map input,
        @NotNull final String basePackageName,
        @NotNull final String subpackageName,
        @NotNull final List<Attribute> fkAttributes)
    {
        input.put("base_package_name", basePackageName);
        input.put("subpackage_name", subpackageName);
        input.put("fk_attributes", fkAttributes);
    }

    /**
     * Fills the parameters required by <code>class</code> rule.
     * @param input the input.
     * @param foreignKey the foreign key.
     * @param engineName the engine name.
     * @param engineVersion the engine version.
     * @param timestamp the timestamp.
     * @param tableRepositoryName the table repository name.
     */
    @SuppressWarnings("unchecked,unused")
    protected void fillClassParameters(
        @NotNull final Map input,
        @NotNull final ForeignKey foreignKey,
        @NotNull final String engineName,
        @NotNull final String engineVersion,
        @NotNull final String timestamp,
        @NotNull final String tableRepositoryName)
    {
        input.put("engine_name", engineName);
        input.put("engine_version", engineVersion);
        input.put("timestamp", timestamp);

        input.put("tr_name", tableRepositoryName);
        input.put("tr_name_normalized", normalize(tableRepositoryName));
        input.put("tr_name_capitalized", capitalize(tableRepositoryName));
    }

    /**
     * Normalizes given value, in lower-case.
     * @param value the value.
     * @param decorationUtils the <code>DecorationUtils</code> instance.
     * @return such output.
     * @precondition value != null
     * @precondition decorationUtils != null
     */
    protected String normalizeLowercase(
        final String value, @NotNull final DecorationUtils decorationUtils)
    {
        return decorationUtils.normalizeLowercase(value);
    }

    /**
     * Capitalizes given value.
     * @param value the value.
     * @param decorationUtils the <code>DecorationUtils</code> instance.
     * @return such output.
     * @precondition value != null
     * @precondition decorationUtils != null
     */
    protected String capitalize(
        @NotNull final String value, @NotNull final DecorationUtils decorationUtils)
    {
        return decorationUtils.capitalize(value);
    }
}
