/*
                  QueryJ Template Packaging

    Copyright (C) 2013-today Jose San Leandro Armendariz
                              queryj@acm-sl.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    Thanks to ACM S.L. for distributing this library under the GPL license.
    Contact info: jose.sanleandro@acm-sl.com
    Postal Address: c/Playa de Lagoa, 1
                    Urb. Valdecabanas
                    Boadilla del monte
                    28660 Madrid
                    Spain

 ******************************************************************************
 *
 * Author: QueryJ's Template Packaging
 *
 * Filename: PerTableTemplatesFeatureTemplateWritingHandler.java
 *
 * Description: Writing handler for PerTableTemplatesFeatureTemplates.
 *
 * Generated by QueryJ Template Packaging's
 * org/acmsl/templates/packaging/TemplateWritingHandler.stg
 * at timestamp: 2013/12/07 12:29
 *
 * DO NOT MODIFY THIS CLASS MANUALLY, SINCE IT GETS GENERATED AUTOMATICALLY.
 * EITHER MODIFY org/acmsl/templates/packaging/TemplateWritingHandler.stg
 * OR CREATE AND APPLY A PATCH.
 */
package org.acmsl.queryj.templates.packaging.handlers;

/*
 * Importing QueryJ-Core classes.
 */
import org.acmsl.queryj.QueryJCommand;
import org.acmsl.queryj.QueryJCommandWrapper;
import org.acmsl.queryj.api.PerRepositoryTemplateContext;
import org.acmsl.queryj.api.handlers.BasePerRepositoryTemplateWritingHandler;
import org.acmsl.queryj.tools.PackageUtils;

/*
 * Importing QueryJ Template Packaging classes.
 */
import org.acmsl.queryj.templates.packaging.exceptions.MissingTemplatesException;
import org.acmsl.queryj.templates.packaging.PerTableTemplatesFeatureTemplate;
import org.acmsl.queryj.templates.packaging.PerTableTemplatesFeatureTemplateGenerator;

/*
 * Importing some JetBrains annotations.
 */
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/*
 * Importing checkthread.org annotations.
 */
import org.checkthread.annotations.ThreadSafe;

/*
 * Importing JDK classes.
 */
import java.io.File;
import java.util.List;

/**
 * Writing handler for {@link PerTableTemplatesFeatureTemplate}s.
 * @author <a href="http://www.acm-sl.org/projects/queryj">QueryJ's Template Packaging</a>
 * Generation template: org/acmsl/templates/packaging/TemplateWritingHandler.stg
 * Created: 2013/12/07 12:29
 */
@ThreadSafe
public class PerTableTemplatesFeatureTemplateWritingHandler
    extends BasePerRepositoryTemplateWritingHandler<
                PerTableTemplatesFeatureTemplate,
                PerRepositoryTemplateContext,
                PerTableTemplatesFeatureTemplateGenerator>
{
    /**
     * Creates a new writing handler for {@link PerTableTemplatesFeatureTemplate templates}.
     */
    public PerTableTemplatesFeatureTemplateWritingHandler() {}

    /**
     * {@inheritDoc}
     */
    @NotNull
    @Override
    protected PerTableTemplatesFeatureTemplateGenerator retrieveTemplateGenerator(final boolean caching, final int threadCount)
    {
        return new PerTableTemplatesFeatureTemplateGenerator(caching, threadCount);
    }

    /**
     * {@inheritDoc}
     */
    @NotNull
    @Override
    protected List<PerTableTemplatesFeatureTemplate> retrieveTemplates(@NotNull final QueryJCommand parameters)
    {
        @NotNull final List<PerTableTemplatesFeatureTemplate> result;

        @Nullable final List<PerTableTemplatesFeatureTemplate> aux =
            new QueryJCommandWrapper<List<PerTableTemplatesFeatureTemplate>>(parameters)
                .getSetting(PerTableTemplatesFeatureTemplateBuildHandler.TEMPLATE_KEY);

        if (aux == null)
        {
            throw new MissingTemplatesException("per-table-templates-feature");
        }
        else
        {
            result = aux;
        }

        return result;
    }

    /**
     * {@inheritDoc}
     */
    @NotNull
    @Override
    protected File retrieveOutputDir(
        @NotNull final File projectFolder,
        @NotNull final String projectPackage,
        final boolean useSubfolders,
        @NotNull final String engineName,
        @NotNull final QueryJCommand parameters,
        @NotNull final PackageUtils packageUtils)
    {
        @NotNull final File result;

        @NotNull final String packageName =
            PerTableTemplatesFeatureTemplateBuildHandler.buildPackageName(
                engineName, projectPackage);

        @NotNull final String[] pieces = packageName.split("\\.");

        @NotNull final StringBuilder aux = new StringBuilder();

        for (@NotNull final String piece : pieces)
        {
            aux.append(piece);
        }

        result = new File(projectFolder.getAbsolutePath() + aux.toString());

        return result;
    }
}
