pipeline {
    agent any

    tools {
        maven 'maven' // Ensure Jenkins uses the right Maven installation
    }

    options {
        skipDefaultCheckout() // Avoids Jenkins auto-checkout
    }

    environment {
        GIT_REPO = 'git@github.com:rydnr/queryj.git'
        CREDENTIALS_ID = 'github' // Jenkins credentials ID for SSH key
        GROUP_ID = 'org.acmsl.queryj'
        ARTIFACT_ID = 'queryj-core'
        MAVEN_REPO = 'http://maven.acm-sl.org/repository/maven-snapshots-local'
        LOCAL_VERSION_FILE = "${WORKSPACE}/.last_snapshot_versions"
        MAVEN_OPTS = "-Dmaven.repo.local=${WORKSPACE}/.m2/repository" // Optional: Isolate repo per build
    }

    stages {
        stage('Build and Deploy') {
            steps {
                withMaven(maven: 'Maven') {  // Enables Jenkins to track SNAPSHOT dependencies
                    sh '/home/jenkins/.sdkman/candidates/maven/current/bin/mvn clean deploy'
                }
            }
        }
    }
}
